### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by avsm**

### CODE REVIEW

**Comment by yminsky** [comment]
Hmm. I tried checking this out and running it, and it didn't work for me:

```
[yminsky@viserion ocaml]$ dune runtest
        test test/output (exit 127)
(cd _build/default/test && ./test.exe) > _build/default/test/output
./test.exe: error while loading shared libraries: librobot_sim.so: cannot open shared object file: No such file or directory
```

**Comment by yminsky** [comment]
Also, I'm still curious about whether the test example is correct in not calling caml_main or caml_startup.  Is init.c supposed to do that, somehow?

**Comment by avsm** [comment]
That's right, the shared library takes care of that, since the idea is that you never see any OCaml from "outside" the shared library -- there is only a C FFI exposed.  The reason init.c works is:

```
__attribute__ ((__constructor__))
void
init(void)
{
  char_os *caml_argv[1] = { NULL };
  caml_startup(caml_argv);
}
```

The constructor attribute ensures it is called when the library is initialised, so the caml engine is fired up behind the scenes.

**Comment by avsm** [comment]
i pushed some linux fixes i needed; link order of test.o was wrong

**Comment by avsm** [comment]
Pushed a fix to the Racket problem and rebased; https://github.com/zevbo/VirtualRobotMania/pull/16/commits/082d8668b073c57f64fa3804ba1faf05c26017cd fixes it.

> Do not use attribute ctor in shared libraries with Racket    
> For some reason, Racket fails with a segfault if a foreign library
> being loaded has any ctors in it.  To get around this, this PR
> modifies the foreign stub generator to create a robotsim_init
> function that initialises the caml runtime.

Enjoy the roboting!

**Pull request merged**
